export type Customer = {
    "id_customer": number,
    "id_shop_group": number,
    "id_shop": number,
    "id_gender": number,
    "id_default_group": number,
    "id_lang": number,
    "id_risk": number,
    "company": string,
    "siret": string,
    "ape": string,
    "firstname": string,
    "lastname": string,
    "email": string,
    "passwd":string,
    "last_passwd_gen": string,
    "birthday": string,
    "newsletter": number,
    "ip_registration_newsletter": string,
    "newsletter_date_add": string,
    "optin": number,
    "website": string,
    "outstanding_allow_amount": number,
    "show_public_prices": number,
    "max_payment_days": number,
    "secure_key": string,
    "note": string,
    "active": number,
    "is_guest": number,
    "deleted": number,
    "date_add": string,
    "date_upd": string,
    "reset_password_token": string,
    "reset_password_validity": string
}
